.TH saidar 1 $Date:\ 2006/11/30\ 23:42:42\ $ i\-scream 
.SH NAME
saidar \- a curses\-based tool for viewing system statistics
.SH SYNOPSIS
\fBsaidar\fR [\-d \fBdelay\fR] [\-c] [\-v] [\-h]
.SH DESCRIPTION
saidar is a curses\-based tool for viewing the
system statistics available through libstatgrab. Statistics include
CPU, processes, load, memory, swap, network I/O, disk I/O, and file
system information.
.SH OPTIONS
The following options are supported.
.TP 
\fB\-d\fR \fIDELAY\fR
Wait DELAY seconds between updates (default 3)
.TP 
\fB\-c\fR
Enables coloured output
.TP 
\fB\-v\fR
Prints the version number
.TP 
\fB\-h\fR
Display help and exits
.SH COLOURED\ OUTPUT
When the \fB\-c\fR option is used saidar uses colours
to display the data. Each area has a different colour to
distinguish it from the nearby fields. Bold and reverse video
effects are used to emphasis fields where necessary.
.PP
The load average figures are displayed in bold when they're
notably (greater that 1) different to each other. This purely
shows that a change in the load is occuring.
.PP
When CPU usage goes over 60% it will be displayed in bold.
At 90% the field is displayed using reverse video. Likewise
for memory, swap and disk usage at 75% and 90%. Zombie
processes are also highlighted.
.PP
Other values (paging, disk I/O and network I/O) are not
highlighted due to the nature of the values; it's not easy
to determine what thresholds are significant.
.SH SEE\ ALSO
\fBstatgrab\fR(1)
\fBstatgrab\fR(3)
.SH AUTHORS
This man page was derived from the man page written by Bartosz
Fenski for the Debian GNU/Linux distribution.
.SH WEBSITE
http://www.i\-scream.org/libstatgrab/
