.TH statgrab\-make\-mrtg\-index 1 $Date:\ 2005/04/25\ 12:37:22\ $ i\-scream 
.SH NAME
statgrab\-make\-mrtg\-index \- generates MRTG configuration
.SH SYNOPSIS
\fBstatgrab\-make\-mrtg\-index\fR [OPTION]\&... [CONFIGFILE]\&...
.SH DESCRIPTION
statgrab\-make\-mrtg\-index generates an XHTML
index page from MRTG configuration files specified on the
command line or read from stdin.
.SH OPTIONS
The following options are supported.
.TP 
\fB\-\-title\fR \fITITLE\fR
Use TITLE as the title of the generated page
.TP 
\fB\-\-help\fR
Display help and exit
.SH SEE\ ALSO
\fBstatgrab\fR(1)
\fBstatgrab\-make\-mrtg\-config\fR(1)
.SH AUTHORS
This man page was derived from the man page written by Bartosz
Fenski for the Debian GNU/Linux distribution.
.SH WEBSITE
http://www.i\-scream.org/libstatgrab/
