.TH PRINTIPROUTE.SH 1 
.ad
.fi
.SH NAME
printiproute.sh
\-
print statisk rute pr. interface
.SH PACKAGE
.ad
.fi
UNItools
.SH SYNOPSIS
.ad
.fi
printiproute
.SH BESKRIVELSE
.ad
.fi
\fCprintiproute(1)\fR anvendes til dokumentation af rute udtryk
pr. interface.

Programmet er ad-hoc.
.SH OPTIONS
.ad
.fi
.TP
html. Udskriv i html til stdout.
.SH SE OGSÅ
.ad
.fi
Dokumentationen for UNItools.
.SH DIAGNOSTICS
.ad
.fi
Programmet er Linux - centrisk og kræver pakken UNItools er installeret.
.SH BUGS
.ad
.fi
Det er der sikkert. Ret dem og send mig en opdatering.
.SH VERSION
.na
.nf
$Date: 2012/12/10 14:05:01 $
.br
$Revision: 1.9 $
.br
$Source: /lan/ssi/projects/UNItools/src/SPLAT/NGX/pkgs/scripts/scripts-1.0/RCS/printiproute,v $
.br
$State: Exp $
.SH HISTORY
.ad
.fi
Se \fCrlog\fR $Id: printiproute,v 1.9 2012/12/10 14:05:01 root Exp $
.SH AUTHOR(S)
.ad
.fi
Niels Thomas Haugård
.br
E-mail: thomas@haugaard.net
.br
UNI\(buC
.br
DTU, Building 304
.br
DK-2800 Kgs. Lyngby
