.TH PRINTNETCOMMENT 1 
.ad
.fi
.SH NAME
printnetcomment
\-
udskriv kommentar mv. for et netværk (netværksobjekt) i Check Point firewall-1
.SH PACKAGE
.ad
.fi
Ingen
.SH SYNOPSIS
.ad
.fi
printnetcomment netværk
.SH BESKRIVELSE
.ad
.fi
Ad-hoc script til dokumentation.
.SH BUGS
.ad
.fi
Små programmer indeholder få fejl, store programmer indeholder mange fejl,
det er menneskeligt at fejle og dette program indeholder også fejl.
Du er velkommen til at finde og rette dem.
.SH VERSION
.na
.nf
$Date: 2007/07/05 10:06:26 $
.br
$Revision: 1.1 $
.br
$Source: /lan/ssi/projects/UNItools/src/SPLAT/NGX/pkgs/scripts/scripts-1.0/RCS/printnetcomment,v $
.br
$State: Exp $
.SH HISTORY
.ad
.fi
Se \fCrlog\fR $Id: printnetcomment,v 1.1 2007/07/05 10:06:26 root Exp $
.SH AUTHOR(S)
.ad
.fi
Niels Thomas Haugård
.br
E-mail: thomas@haugaard.net
.br
UNI\(buC
.br
DTU, Building 304
.br
DK-2800 Kgs. Lyngby
