.TH RESTORE_START_UNIC 1 
.ad
.fi
.SH NAME
restore_start_UNIC
\-
Restore en firewall-1 og operativsystem sikkerhedskopi
.SH PACKAGE
.ad
.fi
UNItools
.SH SYNOPSIS
.ad
.fi
restore_start_UNIC name [<tftp> <ip>]
.SH DESCRIPTION
.ad
.fi
\fCrestore_start_UNIC\fR er identisk med \fC/bin/restore_start\fR,
idet et check for, om firewall-1 kører et fjernet og tre fejl
i Check Points script er rettet.

Det drejer sig om fejl ved \fCif [ -z \fIargument\fR idet
\fIargument\fR skal beskyttes af \fC""\fR for at opfattes som
et argument.
.SH COMMANDS
.ad
.fi
sh(1), tar(1), gzip(1)
.SH SEE ALSO
.ad
.fi

.SH BUGS
.ad
.fi
Ingen kendte.
.SH VERSION
.na
.nf
$Date: 2003/03/02 19:53:58 $
.br
$Revision: 1.1 $
.br
$Source: /var/opt/UNItools/src/scripts/RCS/restore_start_UNIC,v $
.br
$State: Exp $
.SH HISTORY
.ad
.fi
$Log: restore_start_UNIC,v $
Revision 1.1  2003/03/02 19:53:58  root
Initial revision

.SH AUTHOR(S)
.ad
.fi
Check Point Software.
