.TH BACKUP_START_UNIC 1 
.ad
.fi
.SH NAME
backup_start_UNIC
\-
Lav en firewall-1 og operativsystem sikkerhedskopi
.SH PACKAGE
.ad
.fi
UNItools
.SH SYNOPSIS
.ad
.fi
backup_start_UNIC name|cp|all [<tftp> <ip>]
.SH DESCRIPTION
.ad
.fi
\fCbackup_start_UNIC\fR er identisk med \fC/bin/backup_start\fR,
idet et check for, om firewall-1 kører et fjernet.
.SH COMMANDS
.ad
.fi
sh(1), tar(1), gzip(1)
.SH SEE ALSO
.ad
.fi

.SH BUGS
.ad
.fi
Ingen kendte.
.SH VERSION
.na
.nf
$Date: 2005/02/17 00:41:12 $
.br
$Revision: 1.6 $
.br
$Source: /lan/ssi/projects/UNItools/Linux/RedHat_7.3/src/scripts/RCS/backup_start_UNIC,v $
.br
$State: Exp $
.SH HISTORY
.ad
.fi
$Log: backup_start_UNIC,v $
Revision 1.6  2005/02/17 00:41:12  root
tilføjet /var/ace

Revision 1.5  2004/02/25 15:39:11  root
opdateret til R55

Revision 1.4  2003/04/01 07:39:13  root
*** empty log message ***

Revision 1.1  2003/02/21 14:59:48  root
Initial revision

.SH AUTHOR(S)
.ad
.fi
Check Point Software.
