.TH FMOG.PL 1 
.ad
.fi
.SH NAME
fmog.pl
\-
fix/reset or check mode owner and group for files
.SH PACKAGE
.ad
.fi
UNItools
.SH SYNOPSIS
.ad
.fi
fmog.pl \fC[-b | -f | -c ] [ \fIdir\fC ]\fR
.SH DESCRIPTION
.ad
.fi
\fBfmog.pl\fR is not a security utility; the tool is aimed for
checking and resetting permissions and ownership for files to a
known state, eg. after a buggy software installation or
change of configuration files with a wrong umask.

The utility is a filter; it reads it's input from stdin and writes
to stdout.

The utility has tree modes: \fBbuild\fR, \fBcheck\fR and \fBfix\fR.
.SH OPTIONS
.ad
.fi
.TP
\fCfmog.pl --build\fR\ \fIdirectory\fR \fC>\fR \fIfile\fR
Find all files below \fIdir\fR and print \fCuid\fR, \fCgid\fR,
\fCmode\fR, and \fCfile name\fR to stdout. The information is
intented to be saved in a file.
.TP
\fCfmog.pl --check < \fIfile\fR
Read from stdin a list with \fCuid\fR, \fCgid\fR, \fCmode\fR, and
\fCfile name\fR and certify the files in the list has the mode
and permission mentioned there. Complain if that is not the case.

.TP
\fCfmog.pl --fix < \fIfile\fR
Identical to \fCcheck\fR, but files with other mode or permission
than the one in the list is beeing reset to what is in the list.
.SH COMMANDS
.ad
.fi
perl(1)
.SH DIAGNOSTICS
.ad
.fi
None.
.SH BUGS
.ad
.fi
The script uses the \fCperl\fR \fCfind\fR package and may produce
wery large lists.

It continues as best as it can and warns when chmod/chown faills.
.SH WISHLIST
.ad
.fi
Extension of the script to also check for change in file contents,
and the ability to detect added files.
.SH VERSION
.na
.nf
$Date: 2003/02/20 09:17:40 $
.br
$Revision: 1.7 $
.br
$Source: /var/opt/UNItools/src/scripts/RCS/fmog.pl,v $
.br
$State: Exp $
.SH HISTORY
.ad
.fi
See \fCrlog fmog.pl\fR.
.SH AUTHOR(S)
.ad
.fi
Niels Thomas Haugaard
.br
E-mail: thomas@haugaard.net
.br
ECMWF
.br
Shinfield Park
.br
Reading, Berks.
.br
RG2 9AX  England
