/*  This file is automatically generated; changes will be lost.
**
**  If you need to edit this file because "test.syms" didn't do a good
**  job, be sure to save a copy of your changes.
**
**  The "define"s below are simply educated guesses.  If you are
**  having problems compiling, check the appropriate symbol to see if
**  it was set correctly: For each line, if the answer to the question
**  is "no", that line should start with "#undef"; if the answer is
**  yes, it should start with "#define".
*/

#undef  C_PANELSUPPORT          /* Add in panel library function?             */

#undef  C_MENUSUPPORT           /* Add in menu library function?              */

#undef  C_FORMSUPPORT           /* Add in form library function?              */

#define C_ADDCH                 /* Does function 'addch' exist?              */
#define C_ECHOCHAR              /* Does function 'echochar' exist?           */
#define C_ADDCHSTR              /* Does function 'addchstr' exist?           */
#define C_ADDCHNSTR             /* Does function 'addchnstr' exist?          */
#define C_ADDSTR                /* Does function 'addstr' exist?             */
#define C_ADDNSTR               /* Does function 'addnstr' exist?            */
#define C_ATTROFF               /* Does function 'attroff' exist?            */
#define C_ATTRON                /* Does function 'attron' exist?             */
#define C_ATTRSET               /* Does function 'attrset' exist?            */
#define C_STANDEND              /* Does function 'standend' exist?           */
#define C_STANDOUT              /* Does function 'standout' exist?           */
#define C_ATTR_GET              /* Does function 'attr_get' exist?           */
#define C_ATTR_OFF              /* Does function 'attr_off' exist?           */
#define C_ATTR_ON               /* Does function 'attr_on' exist?            */
#define C_ATTR_SET              /* Does function 'attr_set' exist?           */
#define C_CHGAT                 /* Does function 'chgat' exist?              */
#define C_COLOR_PAIR            /* Does function 'COLOR_PAIR' exist?         */
#define C_PAIR_NUMBER           /* Does function 'PAIR_NUMBER' exist?        */
#define C_BEEP                  /* Does function 'beep' exist?               */
#define C_FLASH                 /* Does function 'flash' exist?              */
#define C_BKGD                  /* Does function 'bkgd' exist?               */
#define C_BKGDSET               /* Does function 'bkgdset' exist?            */
#define C_GETBKGD               /* Does function 'getbkgd' exist?            */
#define C_BORDER                /* Does function 'border' exist?             */
#define C_BOX                   /* Does function 'box' exist?                */
#define C_HLINE                 /* Does function 'hline' exist?              */
#define C_VLINE                 /* Does function 'vline' exist?              */
#define C_ERASE                 /* Does function 'erase' exist?              */
#define C_CLEAR                 /* Does function 'clear' exist?              */
#define C_CLRTOBOT              /* Does function 'clrtobot' exist?           */
#define C_CLRTOEOL              /* Does function 'clrtoeol' exist?           */
#define C_START_COLOR           /* Does function 'start_color' exist?        */
#define C_INIT_PAIR             /* Does function 'init_pair' exist?          */
#define C_INIT_COLOR            /* Does function 'init_color' exist?         */
#define C_HAS_COLORS            /* Does function 'has_colors' exist?         */
#define C_CAN_CHANGE_COLOR      /* Does function 'can_change_color' exist?   */
#define C_COLOR_CONTENT         /* Does function 'color_content' exist?      */
#define C_PAIR_CONTENT          /* Does function 'pair_content' exist?       */
#define C_DELCH                 /* Does function 'delch' exist?              */
#define C_DELETELN              /* Does function 'deleteln' exist?           */
#define C_INSDELLN              /* Does function 'insdelln' exist?           */
#define C_INSERTLN              /* Does function 'insertln' exist?           */
#define C_GETCH                 /* Does function 'getch' exist?              */
#define C_UNGETCH               /* Does function 'ungetch' exist?            */
#define C_HAS_KEY               /* Does function 'has_key' exist?            */
#define C_KEY_F                 /* Does function 'KEY_F' exist?              */
#define C_GETSTR                /* Does function 'getstr' exist?             */
#define C_GETNSTR               /* Does function 'getnstr' exist?            */
#define C_GETYX                 /* Does function 'getyx' exist?              */
#define C_GETPARYX              /* Does function 'getparyx' exist?           */
#define C_GETBEGYX              /* Does function 'getbegyx' exist?           */
#define C_GETMAXYX              /* Does function 'getmaxyx' exist?           */
#define C_INCH                  /* Does function 'inch' exist?               */
#define C_INCHSTR               /* Does function 'inchstr' exist?            */
#define C_INCHNSTR              /* Does function 'inchnstr' exist?           */
#define C_INITSCR               /* Does function 'initscr' exist?            */
#define C_ENDWIN                /* Does function 'endwin' exist?             */
#define C_ISENDWIN              /* Does function 'isendwin' exist?           */
#define C_NEWTERM               /* Does function 'newterm' exist?            */
#define C_SET_TERM              /* Does function 'set_term' exist?           */
#define C_DELSCREEN             /* Does function 'delscreen' exist?          */
#define C_CBREAK                /* Does function 'cbreak' exist?             */
#define C_INTCBREAK             /* Does function 'cbreak' return 'int'?      */
#define C_NOCBREAK              /* Does function 'nocbreak' exist?           */
#define C_INTNOCBREAK           /* Does function 'nocbreak' return 'int'?    */
#define C_ECHO                  /* Does function 'echo' exist?               */
#define C_INTECHO               /* Does function 'echo' return 'int'?        */
#define C_NOECHO                /* Does function 'noecho' exist?             */
#define C_INTNOECHO             /* Does function 'noecho' return 'int'?      */
#define C_HALFDELAY             /* Does function 'halfdelay' exist?          */
#define C_INTRFLUSH             /* Does function 'intrflush' exist?          */
#define C_KEYPAD                /* Does function 'keypad' exist?             */
#define C_META                  /* Does function 'meta' exist?               */
#define C_NODELAY               /* Does function 'nodelay' exist?            */
#define C_NOTIMEOUT             /* Does function 'notimeout' exist?          */
#define C_RAW                   /* Does function 'raw' exist?                */
#define C_INTRAW                /* Does function 'raw' return 'int'?         */
#define C_NORAW                 /* Does function 'noraw' exist?              */
#define C_INTNORAW              /* Does function 'noraw' return 'int'?       */
#define C_QIFLUSH               /* Does function 'qiflush' exist?            */
#define C_NOQIFLUSH             /* Does function 'noqiflush' exist?          */
#define C_TIMEOUT               /* Does function 'timeout' exist?            */
#define C_TYPEAHEAD             /* Does function 'typeahead' exist?          */
#define C_INSCH                 /* Does function 'insch' exist?              */
#define C_INSSTR                /* Does function 'insstr' exist?             */
#define C_INSNSTR               /* Does function 'insnstr' exist?            */
#define C_INSTR                 /* Does function 'instr' exist?              */
#define C_INNSTR                /* Does function 'innstr' exist?             */
#define C_DEF_PROG_MODE         /* Does function 'def_prog_mode' exist?      */
#define C_DEF_SHELL_MODE        /* Does function 'def_shell_mode' exist?     */
#define C_RESET_PROG_MODE       /* Does function 'reset_prog_mode' exist?    */
#define C_RESET_SHELL_MODE      /* Does function 'reset_shell_mode' exist?   */
#define C_RESETTY               /* Does function 'resetty' exist?            */
#define C_SAVETTY               /* Does function 'savetty' exist?            */
#define C_GETSYX                /* Does function 'getsyx' exist?             */
#undef  C_INTGETSYX             /* Does function 'getsyx' return 'int'?      */
#define C_SETSYX                /* Does function 'setsyx' exist?             */
#undef  C_INTSETSYX             /* Does function 'setsyx' return 'int'?      */
#define C_CURS_SET              /* Does function 'curs_set' exist?           */
#define C_NAPMS                 /* Does function 'napms' exist?              */
#define C_MOVE                  /* Does function 'move' exist?               */
#define C_CLEAROK               /* Does function 'clearok' exist?            */
#define C_IDLOK                 /* Does function 'idlok' exist?              */
#define C_INTIDLOK              /* Does function 'idlok' return 'int'?       */
#define C_IDCOK                 /* Does function 'idcok' exist?              */
#define C_IMMEDOK               /* Does function 'immedok' exist?            */
#define C_LEAVEOK               /* Does function 'leaveok' exist?            */
#define C_SETSCRREG             /* Does function 'setscrreg' exist?          */
#define C_SCROLLOK              /* Does function 'scrollok' exist?           */
#define C_NL                    /* Does function 'nl' exist?                 */
#define C_INTNL                 /* Does function 'nl' return 'int'?          */
#define C_NONL                  /* Does function 'nonl' exist?               */
#define C_INTNONL               /* Does function 'nonl' return 'int'?        */
#define C_OVERLAY               /* Does function 'overlay' exist?            */
#define C_OVERWRITE             /* Does function 'overwrite' exist?          */
#define C_COPYWIN               /* Does function 'copywin' exist?            */
#define C_NEWPAD                /* Does function 'newpad' exist?             */
#define C_SUBPAD                /* Does function 'subpad' exist?             */
#define C_PREFRESH              /* Does function 'prefresh' exist?           */
#define C_PNOUTREFRESH          /* Does function 'pnoutrefresh' exist?       */
#define C_PECHOCHAR             /* Does function 'pechochar' exist?          */
#define C_REFRESH               /* Does function 'refresh' exist?            */
#define C_NOUTREFRESH           /* Does function 'noutrefresh' exist?        */
#define C_DOUPDATE              /* Does function 'doupdate' exist?           */
#define C_REDRAWWIN             /* Does function 'redrawwin' exist?          */
#define C_REDRAWLN              /* Does function 'redrawln' exist?           */
#define C_SCR_DUMP              /* Does function 'scr_dump' exist?           */
#define C_SCR_RESTORE           /* Does function 'scr_restore' exist?        */
#define C_SCR_INIT              /* Does function 'scr_init' exist?           */
#define C_SCR_SET               /* Does function 'scr_set' exist?            */
#define C_SCROLL                /* Does function 'scroll' exist?             */
#define C_SCRL                  /* Does function 'scrl' exist?               */
#define C_SLK_INIT              /* Does function 'slk_init' exist?           */
#define C_SLK_SET               /* Does function 'slk_set' exist?            */
#define C_SLK_REFRESH           /* Does function 'slk_refresh' exist?        */
#define C_SLK_NOUTREFRESH       /* Does function 'slk_noutrefresh' exist?    */
#define C_SLK_LABEL             /* Does function 'slk_label' exist?          */
#define C_SLK_CLEAR             /* Does function 'slk_clear' exist?          */
#define C_SLK_RESTORE           /* Does function 'slk_restore' exist?        */
#define C_SLK_TOUCH             /* Does function 'slk_touch' exist?          */
#define C_SLK_ATTRON            /* Does function 'slk_attron' exist?         */
#define C_SLK_ATTRSET           /* Does function 'slk_attrset' exist?        */
#define C_SLK_ATTR              /* Does function 'slk_attr' exist?           */
#define C_SLK_ATTROFF           /* Does function 'slk_attroff' exist?        */
#define C_SLK_COLOR             /* Does function 'slk_color' exist?          */
#define C_BAUDRATE              /* Does function 'baudrate' exist?           */
#define C_ERASECHAR             /* Does function 'erasechar' exist?          */
#define C_HAS_IC                /* Does function 'has_ic' exist?             */
#define C_HAS_IL                /* Does function 'has_il' exist?             */
#define C_KILLCHAR              /* Does function 'killchar' exist?           */
#define C_TERMATTRS             /* Does function 'termattrs' exist?          */
#define C_TERMNAME              /* Does function 'termname' exist?           */
#define C_TOUCHWIN              /* Does function 'touchwin' exist?           */
#define C_UNTOUCHWIN            /* Does function 'untouchwin' exist?         */
#define C_TOUCHLN               /* Does function 'touchln' exist?            */
#define C_IS_LINETOUCHED        /* Does function 'is_linetouched' exist?     */
#define C_IS_WINTOUCHED         /* Does function 'is_wintouched' exist?      */
#define C_UNCTRL                /* Does function 'unctrl' exist?             */
#define C_KEYNAME               /* Does function 'keyname' exist?            */
#define C_FILTER                /* Does function 'filter' exist?             */
#undef  C_INTFILTER             /* Does function 'filter' return 'int'?      */
#define C_USE_ENV               /* Does function 'use_env' exist?            */
#define C_PUTWIN                /* Does function 'putwin' exist?             */
#define C_GETWIN                /* Does function 'getwin' exist?             */
#define C_DELAY_OUTPUT          /* Does function 'delay_output' exist?       */
#define C_FLUSHINP              /* Does function 'flushinp' exist?           */
#define C_NEWWIN                /* Does function 'newwin' exist?             */
#define C_DELWIN                /* Does function 'delwin' exist?             */
#define C_MVWIN                 /* Does function 'mvwin' exist?              */
#define C_SUBWIN                /* Does function 'subwin' exist?             */
#define C_DERWIN                /* Does function 'derwin' exist?             */
#define C_MVDERWIN              /* Does function 'mvderwin' exist?           */
#define C_DUPWIN                /* Does function 'dupwin' exist?             */
#define C_SYNCUP                /* Does function 'syncup' exist?             */
#define C_SYNCOK                /* Does function 'syncok' exist?             */
#define C_CURSYNCUP             /* Does function 'cursyncup' exist?          */
#define C_SYNCDOWN              /* Does function 'syncdown' exist?           */
#define C_GETMOUSE              /* Does function 'getmouse' exist?           */
#define C_UNGETMOUSE            /* Does function 'ungetmouse' exist?         */
#define C_MOUSEMASK             /* Does function 'mousemask' exist?          */
#define C_ENCLOSE               /* Does function 'enclose' exist?            */
#define C_MOUSE_TRAFO           /* Does function 'mouse_trafo' exist?        */
#define C_MOUSEINTERVAL         /* Does function 'mouseinterval' exist?      */
#define C_BUTTON_RELEASE        /* Does function 'BUTTON_RELEASE' exist?     */
#define C_BUTTON_PRESS          /* Does function 'BUTTON_PRESS' exist?       */
#define C_BUTTON_CLICK          /* Does function 'BUTTON_CLICK' exist?       */
#define C_BUTTON_DOUBLE_CLICK   /* Does function 'BUTTON_DOUBLE_CLICK' exist?*/
#define C_BUTTON_TRIPLE_CLICK   /* Does function 'BUTTON_TRIPLE_CLICK' exist?*/
#define C_BUTTON_RESERVED_EVENT /* Does function 'BUTTON_RESERVED_EVENT' exist?*/
#define C_USE_DEFAULT_COLORS    /* Does function 'use_default_colors' exist? */
#define C_ASSUME_DEFAULT_COLORS /* Does function 'assume_default_colors' exist?*/
#define C_DEFINE_KEY            /* Does function 'define_key' exist?         */
#define C_KEYBOUND              /* Does function 'keybound' exist?           */
#define C_KEYOK                 /* Does function 'keyok' exist?              */
#define C_RESIZETERM            /* Does function 'resizeterm' exist?         */
#define C_RESIZE                /* Does function 'resize' exist?             */
#define C_GETMAXY               /* Does function 'getmaxy' exist?            */
#define C_GETMAXX               /* Does function 'getmaxx' exist?            */
#undef  C_FLUSOK                /* Does function 'flusok' exist?             */
#undef  C_GETCAP                /* Does function 'getcap' exist?             */
#undef  C_TOUCHOVERLAP          /* Does function 'touchoverlap' exist?       */
#undef  C_NEW_PANEL             /* Does function 'new_panel' exist?          */
#undef  C_BOTTOM_PANEL          /* Does function 'bottom_panel' exist?       */
#undef  C_TOP_PANEL             /* Does function 'top_panel' exist?          */
#undef  C_SHOW_PANEL            /* Does function 'show_panel' exist?         */
#undef  C_UPDATE_PANELS         /* Does function 'update_panels' exist?      */
#undef  C_HIDE_PANEL            /* Does function 'hide_panel' exist?         */
#undef  C_PANEL_WINDOW          /* Does function 'panel_window' exist?       */
#undef  C_REPLACE_PANEL         /* Does function 'replace_panel' exist?      */
#undef  C_MOVE_PANEL            /* Does function 'move_panel' exist?         */
#undef  C_PANEL_HIDDEN          /* Does function 'panel_hidden' exist?       */
#undef  C_PANEL_ABOVE           /* Does function 'panel_above' exist?        */
#undef  C_PANEL_BELOW           /* Does function 'panel_below' exist?        */
#undef  C_SET_PANEL_USERPTR     /* Does function 'set_panel_userptr' exist?  */
#undef  C_PANEL_USERPTR         /* Does function 'panel_userptr' exist?      */
#undef  C_DEL_PANEL             /* Does function 'del_panel' exist?          */
#undef  C_SET_MENU_FORE         /* Does function 'set_menu_fore' exist?      */
#undef  C_MENU_FORE             /* Does function 'menu_fore' exist?          */
#undef  C_SET_MENU_BACK         /* Does function 'set_menu_back' exist?      */
#undef  C_MENU_BACK             /* Does function 'menu_back' exist?          */
#undef  C_SET_MENU_GREY         /* Does function 'set_menu_grey' exist?      */
#undef  C_MENU_GREY             /* Does function 'menu_grey' exist?          */
#undef  C_SET_MENU_PAD          /* Does function 'set_menu_pad' exist?       */
#undef  C_MENU_PAD              /* Does function 'menu_pad' exist?           */
#undef  C_POS_MENU_CURSOR       /* Does function 'pos_menu_cursor' exist?    */
#undef  C_MENU_DRIVER           /* Does function 'menu_driver' exist?        */
#undef  C_SET_MENU_FORMAT       /* Does function 'set_menu_format' exist?    */
#undef  C_MENU_FORMAT           /* Does function 'menu_format' exist?        */
#undef  C_SET_MENU_ITEMS        /* Does function 'set_menu_items' exist?     */
#undef  C_MENU_ITEMS            /* Does function 'menu_items' exist?         */
#undef  C_ITEM_COUNT            /* Does function 'item_count' exist?         */
#undef  C_SET_MENU_MARK         /* Does function 'set_menu_mark' exist?      */
#undef  C_MENU_MARK             /* Does function 'menu_mark' exist?          */
#undef  C_NEW_MENU              /* Does function 'new_menu' exist?           */
#undef  C_FREE_MENU             /* Does function 'free_menu' exist?          */
#undef  C_MENU_OPTS             /* Does function 'menu_opts' exist?          */
#undef  C_SET_MENU_OPTS         /* Does function 'set_menu_opts' exist?      */
#undef  C_MENU_OPTS_ON          /* Does function 'menu_opts_on' exist?       */
#undef  C_MENU_OPTS_OFF         /* Does function 'menu_opts_off' exist?      */
#undef  C_SET_MENU_PATTERN      /* Does function 'set_menu_pattern' exist?   */
#undef  C_MENU_PATTERN          /* Does function 'menu_pattern' exist?       */
#undef  C_POST_MENU             /* Does function 'post_menu' exist?          */
#undef  C_UNPOST_MENU           /* Does function 'unpost_menu' exist?        */
#undef  C_SET_MENU_USERPTR      /* Does function 'set_menu_userptr' exist?   */
#undef  C_MENU_USERPTR          /* Does function 'menu_userptr' exist?       */
#undef  C_SET_MENU_WIN          /* Does function 'set_menu_win' exist?       */
#undef  C_MENU_WIN              /* Does function 'menu_win' exist?           */
#undef  C_SET_MENU_SUB          /* Does function 'set_menu_sub' exist?       */
#undef  C_MENU_SUB              /* Does function 'menu_sub' exist?           */
#undef  C_SCALE_MENU            /* Does function 'scale_menu' exist?         */
#undef  C_SET_CURRENT_ITEM      /* Does function 'set_current_item' exist?   */
#undef  C_CURRENT_ITEM          /* Does function 'current_item' exist?       */
#undef  C_SET_TOP_ROW           /* Does function 'set_top_row' exist?        */
#undef  C_TOP_ROW               /* Does function 'top_row' exist?            */
#undef  C_ITEM_INDEX            /* Does function 'item_index' exist?         */
#undef  C_ITEM_NAME             /* Does function 'item_name' exist?          */
#undef  C_ITEM_DESCRIPTION      /* Does function 'item_description' exist?   */
#undef  C_NEW_ITEM              /* Does function 'new_item' exist?           */
#undef  C_FREE_ITEM             /* Does function 'free_item' exist?          */
#undef  C_SET_ITEM_OPTS         /* Does function 'set_item_opts' exist?      */
#undef  C_ITEM_OPTS_ON          /* Does function 'item_opts_on' exist?       */
#undef  C_ITEM_OPTS_OFF         /* Does function 'item_opts_off' exist?      */
#undef  C_ITEM_OPTS             /* Does function 'item_opts' exist?          */
#undef  C_ITEM_USERPTR          /* Does function 'item_userptr' exist?       */
#undef  C_SET_ITEM_USERPTR      /* Does function 'set_item_userptr' exist?   */
#undef  C_SET_ITEM_VALUE        /* Does function 'set_item_value' exist?     */
#undef  C_ITEM_VALUE            /* Does function 'item_value' exist?         */
#undef  C_ITEM_VISIBLE          /* Does function 'item_visible' exist?       */
#undef  C_MENU_REQUEST_NAME     /* Does function 'menu_request_name' exist?  */
#undef  C_MENU_REQUEST_BY_NAME  /* Does function 'menu_request_by_name' exist?*/
#undef  C_SET_MENU_SPACING      /* Does function 'set_menu_spacing' exist?   */
#undef  C_MENU_SPACING          /* Does function 'menu_spacing' exist?       */
#undef  C_POS_FORM_CURSOR       /* Does function 'pos_form_cursor' exist?    */
#undef  C_DATA_AHEAD            /* Does function 'data_ahead' exist?         */
#undef  C_DATA_BEHIND           /* Does function 'data_behind' exist?        */
#undef  C_FORM_DRIVER           /* Does function 'form_driver' exist?        */
#undef  C_SET_FORM_FIELDS       /* Does function 'set_form_fields' exist?    */
#undef  C_FORM_FIELDS           /* Does function 'form_fields' exist?        */
#undef  C_FIELD_COUNT           /* Does function 'field_count' exist?        */
#undef  C_MOVE_FIELD            /* Does function 'move_field' exist?         */
#undef  C_NEW_FORM              /* Does function 'new_form' exist?           */
#undef  C_FREE_FORM             /* Does function 'free_form' exist?          */
#undef  C_SET_NEW_PAGE          /* Does function 'set_new_page' exist?       */
#undef  C_NEW_PAGE              /* Does function 'new_page' exist?           */
#undef  C_SET_FORM_OPTS         /* Does function 'set_form_opts' exist?      */
#undef  C_FORM_OPTS_ON          /* Does function 'form_opts_on' exist?       */
#undef  C_FORM_OPTS_OFF         /* Does function 'form_opts_off' exist?      */
#undef  C_FORM_OPTS             /* Does function 'form_opts' exist?          */
#undef  C_SET_CURRENT_FIELD     /* Does function 'set_current_field' exist?  */
#undef  C_CURRENT_FIELD         /* Does function 'current_field' exist?      */
#undef  C_SET_FORM_PAGE         /* Does function 'set_form_page' exist?      */
#undef  C_FORM_PAGE             /* Does function 'form_page' exist?          */
#undef  C_FIELD_INDEX           /* Does function 'field_index' exist?        */
#undef  C_POST_FORM             /* Does function 'post_form' exist?          */
#undef  C_UNPOST_FORM           /* Does function 'unpost_form' exist?        */
#undef  C_SET_FORM_USERPTR      /* Does function 'set_form_userptr' exist?   */
#undef  C_FORM_USERPTR          /* Does function 'form_userptr' exist?       */
#undef  C_SET_FORM_WIN          /* Does function 'set_form_win' exist?       */
#undef  C_FORM_WIN              /* Does function 'form_win' exist?           */
#undef  C_SET_FORM_SUB          /* Does function 'set_form_sub' exist?       */
#undef  C_FORM_SUB              /* Does function 'form_sub' exist?           */
#undef  C_SCALE_FORM            /* Does function 'scale_form' exist?         */
#undef  C_SET_FIELD_FORE        /* Does function 'set_field_fore' exist?     */
#undef  C_FIELD_FORE            /* Does function 'field_fore' exist?         */
#undef  C_SET_FIELD_BACK        /* Does function 'set_field_back' exist?     */
#undef  C_FIELD_BACK            /* Does function 'field_back' exist?         */
#undef  C_SET_FIELD_PAD         /* Does function 'set_field_pad' exist?      */
#undef  C_FIELD_PAD             /* Does function 'field_pad' exist?          */
#undef  C_SET_FIELD_BUFFER      /* Does function 'set_field_buffer' exist?   */
#undef  C_FIELD_BUFFER          /* Does function 'field_buffer' exist?       */
#undef  C_SET_FIELD_STATUS      /* Does function 'set_field_status' exist?   */
#undef  C_FIELD_STATUS          /* Does function 'field_status' exist?       */
#undef  C_SET_MAX_FIELD         /* Does function 'set_max_field' exist?      */
#undef  C_FIELD_INFO            /* Does function 'field_info' exist?         */
#undef  C_DYNAMIC_FIELD_INFO    /* Does function 'dynamic_field_info' exist? */
#undef  C_SET_FIELD_JUST        /* Does function 'set_field_just' exist?     */
#undef  C_FIELD_JUST            /* Does function 'field_just' exist?         */
#undef  C_NEW_FIELD             /* Does function 'new_field' exist?          */
#undef  C_DUP_FIELD             /* Does function 'dup_field' exist?          */
#undef  C_LINK_FIELD            /* Does function 'link_field' exist?         */
#undef  C_FREE_FIELD            /* Does function 'free_field' exist?         */
#undef  C_SET_FIELD_OPTS        /* Does function 'set_field_opts' exist?     */
#undef  C_FIELD_OPTS_ON         /* Does function 'field_opts_on' exist?      */
#undef  C_FIELD_OPTS_OFF        /* Does function 'field_opts_off' exist?     */
#undef  C_FIELD_OPTS            /* Does function 'field_opts' exist?         */
#undef  C_SET_FIELD_USERPTR     /* Does function 'set_field_userptr' exist?  */
#undef  C_FIELD_USERPTR         /* Does function 'field_userptr' exist?      */
#undef  C_FIELD_ARG             /* Does function 'field_arg' exist?          */
#undef  C_FORM_REQUEST_NAME     /* Does function 'form_request_name' exist?  */
#undef  C_FORM_REQUEST_BY_NAME  /* Does function 'form_request_by_name' exist?*/
#define C_LINES                 /* Does variable 'LINES' exist?              */
#define C_COLS                  /* Does variable 'COLS' exist?               */
#define C_STDSCR                /* Does variable 'stdscr' exist?             */
#define C_CURSCR                /* Does variable 'curscr' exist?             */
#define C_COLORS                /* Does variable 'COLORS' exist?             */
#define C_COLOR_PAIRS           /* Does variable 'COLOR_PAIRS' exist?        */
#define C_TYPATTR_T             /* Does typedef 'attr_t' exist?              */
#define C_TYPBOOL               /* Does typedef 'bool' exist?                */
#define C_TYPCHTYPE             /* Does typedef 'chtype' exist?              */
#define C_TYPMEVENT             /* Does typedef 'MEVENT' exist?              */
#define C_TYPMMASK_T            /* Does typedef 'mmask_t' exist?             */
#define C_TYPSCREEN             /* Does typedef 'SCREEN' exist?              */
